### ISSUE TITLE
Should parse both /sed and /sed@<botname> the same

### ISSUE THREAD

**Issue by gussmith23** [gussmith23/sedbot#2]
Currently, if someone runs via /sed@<botname>, it sends <botname> to the command line as an argument to sed.

**Comment by Amar1729** [comment]
Quick look - could [this line](https://github.com/gussmith23/sedbot/blob/523053b6724d4df2cdb20dd349c4607f638424d4/sedbot.sh#L15) be the issue?  

You're cutting off the string after the first five characters, but instead should do something like:  
`sed_cmd = $(echo $text | cut -f2 -d' ')`
